[workspace]
authors = ["Kyle Carow <kylecarow@gmail.com>"]
channels = ["conda-forge"]
name = "fastsim-vehicles"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build-index = { cmd = "cargo run --", cwd = "tools/build-index" }

[dependencies]
